import './models/Car.dart';

List<Car> carsList = [
  Car(
    carID: '001',
    carName: 'Altis Grande',
    carType: carTypes.sedan,
    carEngine: "1800 CC",
    carRate: 3000,
    carImage: "assets/images/grande.png",
    carMake: 'Toyota',
  ),
  Car(
    carID: '002',
    carName: 'Camry',
    carType: carTypes.sedan,
    carEngine: "1800 CC",
    carRate: 4000,
    carImage: "assets/images/camry.png",
    carMake: 'Toyota',
  ),
  Car(
    carID: '003',
    carName: 'Fortuner',
    carType: carTypes.suv,
    carEngine: "2700 CC",
    carRate: 6000,
    carImage: "assets/images/fortuner.png",
    carMake: 'Toyota',
  ),
  Car(
    carID: '007',
    carName: 'Yaris',
    carType: carTypes.sedan,
    carEngine: "1500 CC",
    carRate: 2500,
    carImage: "assets/images/yaris.png",
    carMake: 'Toyota',
  ),
  Car(
    carID: '004',
    carName: 'Land Cruiser',
    carType: carTypes.suv,
    carEngine: "3500 CC",
    carRate: 9000,
    carImage: "assets/images/landcruiser.png",
    carMake: 'Toyota',
  ),
  Car(
    carID: '005',
    carName: 'Prius',
    carType: carTypes.hatchback,
    carEngine: "1500 CC",
    carRate: 3000,
    carImage: "assets/images/prius.png",
    carMake: 'Toyota',
  ),
  Car(
    carID: '006',
    carName: 'Revo',
    carType: carTypes.truck,
    carEngine: "2200 CC",
    carRate: 5000,
    carImage: "assets/images/revo.png",
    carMake: 'Toyota',
  ),
  Car(
    carID: '007',
    carName: 'Rush',
    carType: carTypes.hatchback,
    carEngine: "1500 CC",
    carRate: 2500,
    carImage: "assets/images/rush.png",
    carMake: 'Toyota',
  ),
];
